[theme]
primaryColor = "#007BFF"   # Blue color for buttons
backgroundColor = "#FFFFFF" # White background
secondaryBackgroundColor = "#F0F2F6" # Light gray sidebar
textColor = "#000000"       # Black text
font = "sans serif"         # Modern readable font
